// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTask() {
  return window['go']['main']['App']['GetTask']();
}

export function GetTimer() {
  return window['go']['main']['App']['GetTimer']();
}

export function PauseTimer() {
  return window['go']['main']['App']['PauseTimer']();
}

export function ResetTimer() {
  return window['go']['main']['App']['ResetTimer']();
}

export function SetTask(arg1) {
  return window['go']['main']['App']['SetTask'](arg1);
}

export function StartTimer(arg1) {
  return window['go']['main']['App']['StartTimer'](arg1);
}
