// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSessionHistory() {
  return window['go']['main']['App']['GetSessionHistory']();
}

export function GetSessionsByDate(arg1) {
  return window['go']['main']['App']['GetSessionsByDate'](arg1);
}

export function GetTask() {
  return window['go']['main']['App']['GetTask']();
}

export function GetTimer() {
  return window['go']['main']['App']['GetTimer']();
}

export function PauseTimer() {
  return window['go']['main']['App']['PauseTimer']();
}

export function ResetTimer() {
  return window['go']['main']['App']['ResetTimer']();
}

export function SaveCompletedSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveCompletedSession'](arg1, arg2, arg3);
}

export function SavePartialSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['SavePartialSession'](arg1, arg2, arg3);
}

export function SetTask(arg1) {
  return window['go']['main']['App']['SetTask'](arg1);
}

export function SetWindowHeight(arg1) {
  return window['go']['main']['App']['SetWindowHeight'](arg1);
}

export function StartTimer(arg1) {
  return window['go']['main']['App']['StartTimer'](arg1);
}
