// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTask():Promise<string>;

export function GetTimer():Promise<any>;

export function PauseTimer():Promise<void>;

export function ResetTimer():Promise<void>;

export function SetTask(arg1:string):Promise<void>;

export function StartTimer(arg1:number):Promise<void>;
